### ISSUE TITLE
References for Research Data Management

### ISSUE THREAD

**Issue by chrzyki** [cldf/cldf-paper#1]
(From the other repository)

Publications from the following list might be useful in the introduction to cement points like “[a]s the move towards open and replicable science grows, more publications are …” and “replicability and usability”. They all have somewhat different foci and, as such, some might not be a perfect fit for the article that you have in mind. At the end of the list there are also a couple of (I think) very well-written German manuals on research data management, data life cycles, etc. However, I’m not sure how useful German publications are going to be for your article.

# English Publications

* The Research & Innovation Directorate-General from the European Commission publishes a number of guidelines dealing with open access and data management. The website listing all the materials can be found [here](http://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/open-access-dissemination_en.htm) and the most important (most citable) document is probably [this](http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-pilot-guide_en.pdf) one, dealing with general guidelines on open access, scientific publications, and research data management.

```
@manual{eu2017a,
	title={H2020 Programme: Guidelines to the Rules on Open Access to Scientific Publications and Open Access to Research Data in Horizon 2020},
	organization={European Commission: Directorate-General for Research & Innovation},
	year={2017}
```

* A short but somewhat citable article on research data management in Nature. PDF can be found [here](https://www.nature.com/naturejobs/2016/160107/pdf/nj7584-117a.pdf).

```
@article{gewin2016a,
  title={Data Sharing: An Open Mind on Open Data},
  author={Gewin, Virginia},
  journal={Nature},
  volume={529},
  number={7584},
  pages={117--119},
  year={2016},
  publisher={Nature Research}
}
```

* Guidelines on the Handling of Research Data in Biodiversity Research [here](http://www.dfg.de/en/research_funding/announcements_proposals/2015/info_wissenschaft_15_36/index.html) and [here](http://www.dfg.de/download/pdf/foerderung/antragstellung/forschungsdaten/guidelines_biodiversity_research.pdf) as PDF. The focus is biology/biodiversity, but the checklist that is included with the article is very well done.

```
@manual{dfg2015a,
	title={Guidelines on the Handling of Research Data in Biodiversity Research},
	organization={Deutsche Forschungsgemeinschaft},
	year={2015}
```

# Websites

* The [Linguistic Data Consortium (LDC)](https://www.ldc.upenn.edu/data-management/data-management-plans) provides information on data management plans in linguistic research contexts.
* The [Research Data Alliance (RDA)](https://www.rd-alliance.org/rda-disciplines/rda-and-digital-humanities) provides information on data sharing in the (digital) humanities.
* The [Alliance Permanent Access (APA)](http://www.alliancepermanentaccess.org/) helps with managing data throughout its life cycle.
* [DataOne](https://www.dataone.org/data-management-planning) does have a wealth of information on research data management in US-centric contexts.

# German Publications

* A comprehensive guide on digitalising information, can be found [here](http://www.dfg.de/formulare/12_151/12_151_de.pdf). Particularly interesting is section 3, dealing with recommendations for data formats and metadata.

```
@manual{dfg2016a,
	title={DFG-Praxisregeln „Digitalisierung“},
	organization={Deutsche Forschungsgemeinschaft},
	year={2016}
```

* Field reports on implementing different techniques and strategies for research data management are provided by the Ministerium für Wissenschaft, Forschung und Kunst (Baden-Württemberg). The PDF is available [here](https://mwk.baden-wuerttemberg.de/fileadmin/redaktion/m-mwk/intern/dateien/pdf/Forschung/066_PM_Anlage_E-Science_Web.pdf).

```
@manual{escience2014a,
	title={E-Science: Wissenschaft unter neuen Rahmenbedingungen. Fachkonzept zur Weiterentwicklung der wissenschaftlichen Infrastruktur in Baden-Württemberg},
	organization={Ministerium für Wissenschaft, Forschung und Kunst (Baden-Württemberg)},
	year={2014}
```

* Leitfaden zum Forschungsdatenmanagement, available [here](http://www.wissgrid.de/publikationen/Leitfaden_Data-Management-WissGrid.pdf). Noteworthy for its well-done representation of research data in conjunction with its life cycle (before a project, during a project, after a project, …).

```
@article{ludwig2013a,
  title={Leitfaden zum Forschungsdatenmanagement},
  author={Ludwig, Jens and Enke, Harry},
  journal={Ergebnisse aus dem WissGrid-Projekt},
  volume={15},
  pages={120},
  year={2013}
}
```

**Comment by LinguList** [comment]
As we quote this a lot, we should enhance our table in the current version, showing the PRAHTICE-principles by comparing with their Leitfaden, this makes it a part for the discussion.

**Comment by LinguList** [comment]
we can close this, right? I mean, my last comment may still be valid, but the question is to which degree people will really follow up on this, so maybe we just leave it there...
