### ISSUE TITLE
Mention Spring School and Software/Data-Carpentry

### ISSUE THREAD

**Issue by xrotwang** [cldf/cldf-paper#13]
highlighting the potential of CLDF

**Comment by LinguList** [comment]
If there's space, mentioning thus: http://site.uit.no/linguisticsdatacitation, may also be useful, saying that we work in their direction...

**Comment by LinguList** [comment]
This is something for the discussion, right? I'll add a label.

**Comment by LinguList** [comment]
Maybe we can leave this out for now?

**Comment by xrotwang** [comment]
yes
