### ISSUE TITLE
wide and narrow data format: check original source

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf-paper#16]
Wikipedia lists: 

* Thompson, M. E. (1997), Theory of sample surveys, Chapman & Hall, London. 

and

* Chantala, K. (2006) "Using STATA to Analyze data from a Sample Survey". 1-10-2001. UNC Chapel Hill, Carolina Population Center. 10-1-2006.

One of us should trace one of those books and confirm that it talks about wide and narrow data distinction, so we can quote it instead of quoting wikipedia.

**Comment by LinguList** [comment]
BTW: wikipedia is here: https://en.wikipedia.org/wiki/Wide_and_narrow_data

**Comment by LinguList** [comment]
I'll quote Thompson for the time being.

**Comment by LinguList** [comment]
BTW: can't we say that we follow an [entity-attribute-value model](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model)?

**Comment by xrotwang** [comment]
No, we explicitly do not follow EAV. If we would, we wouldn't have properties defined in the ontology which are used as `propertyUrl`s.

**Comment by LinguList** [comment]
Okay, I see.

**Comment by LinguList** [comment]
It's actually good: one thing less to quote...

**Comment by xrotwang** [comment]
I just looked up where it's quoted. We actually should remove any mention of wide-vs-narrow completely, since we don't stick to any of it completely.

**Comment by LinguList** [comment]
I'll rephrase it as "explicitenes" and say: Put one type of value into a cell, don't mix different data points in one cell. Should be explicit enough to understand, and we get rid of the quote.

**Comment by LinguList** [comment]
okay, deleted this with my last pr
