### ISSUE TITLE
Box/Figure 2: Data Model (Section 2.1)

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf-paper#5]
We need an UML-like thingy to introduce the data model.

**Comment by xrotwang** [comment]
Dunno. There is no general data model across all modules. We could use the `clld` data model and show how it fits CLDF.

Alternatively, we could stick to the very core: I.e. datapoints are typically triples (language, parameter, value) with a many-to-many relation to sources.

**Comment by LinguList** [comment]
I have an idea now. We were discussing this, I think, in my office: have a table in which the modules are compared and we add, which parts are standardized. This would suffice now, I think. I think i pasted the table somewhere in another issue.

**Comment by LinguList** [comment]
#11 takes care of this
