### ISSUE TITLE
Elaborate Section 2.1 Data Model

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf-paper#7]
So far, we have the following situation:

1. languages / doculects are always constant, described by Glottolog
2. parameters differ, for wordlist, we have Concepticon, for Features, we could have Grammaticon, but we don't have it yet, for dictionaries, we have custom parameters (senses)
3. Values are *form* for Wordlist, *value* for Structure, and *orthographicform* or similar for dictionary

I am having a few problems in understanding where we have the trias of language/parameter/value in all three different dataset types. A table would be helpful to illustrate this, also for the text.

**Comment by xrotwang** [comment]
See also #11

**Comment by LinguList** [comment]
Yes, #11 is duplicate.
