### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by LinguList** [cldf/cldf-paper#9]
This still needs refinements, we should please make sure who will work on this next. The text does not read very smoothly, the two examples could be shortened, and we need to add the table.

**Comment by SimonGreenhill** [comment]
Yes, my turn. Hopefully I can get some time soon!

**Comment by LinguList** [comment]
luckily this was 25 days ago, the text reads better now, I think, but double-checking is still needed, and the FAIR-table for dictionaries needs to be checked to show that the dictionary formats are not FAIR (or use another example)

**Comment by LinguList** [comment]
I think we can close this. All further critics will be dealt with when everybody re-reads and comments on the draft.
